# Generated by Django 5.1.1 on 2024-09-24 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("system", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Statement",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("academic_year", models.CharField(max_length=4, verbose_name="学年")),
                ("total", models.FloatField(default=0.0, verbose_name="总工作量")),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="statement_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="system.department",
                        verbose_name="所属单位",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="system.teacher",
                        verbose_name="教师ID",
                    ),
                ),
                (
                    "updator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="statement_updator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作量明细",
                "verbose_name_plural": "工作量明细",
            },
        ),
    ]
