# Generated by Django 5.1.1 on 2024-09-24 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("statement", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statement",
            name="department",
        ),
    ]
